name: pfc
channels: [conda-forge, pytorch]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pip
  - pip:
      - numpy
      - opencv-python
      - matplotlib
      - tqdm
      - pycocotools